### ISSUE TITLE
bitcoin/payment/redirect infinite redirect loop

### ISSUE THREAD

**Issue by JayShore** [MtGox/magento#10]
This script can face infinite redirect when a browser back button is pressed after successful redirection to mtgox for payment.

**Comment by jgautheron** [comment]
Hi, my last update (1.0.5) changed the redirection delay to 5 secs, therefore you should be able to get to the page preceding the redirection without problem.

**Comment by rintema** [comment]
I still have the infinite redirect loop. I have installed 1.0.5. Any idea what the problem might be?

**Comment by Flynsarmy** [comment]
I'm also experiencing infinate redirect loop after completing an order. I don't press the back button or anything, just finish checkout and get stuck on the "You will be redirected to the MtGox Payment Platform within 5 seconds." page.

**Comment by maxanoo** [comment]
same as Flynsarmy

please checkout the problem here:
www.anuschka-shop.nl
does anyone knows how to solve this?
![6534f18b-fdb4-40a6-a891-72ba24853bfa](https://f.cloud.github.com/assets/4173410/387391/12bf74be-a6c0-11e2-9cda-29f00e8361b4.jpg)
![0f71722b-aa29-40ea-b380-eb2970d92cc0](https://f.cloud.github.com/assets/4173410/387396/3df590e6-a6c0-11e2-8af6-00d079dad869.jpg)

plus, the prices are not correct.
i tried to purchase a product which costs 399€ and my site says its BTC 767,52
(value today: BTC 1 = EUR 55)

i think i did a mistake in the config, but cant find it.

**Comment by maxanoo** [comment]
update:
see this error in magentos system.log
Notice: Undefined index: return  in /app/code/community/Mtgox/Bitcoin/controllers/PaymentController.php on line 23

which is
$form->setAction($responseData['return']['payment_url'])

any ideas?

**Comment by bruvv** [comment]
Same issue here

and also getting: 

```
[MtGoxPayment] login_error_missing_rest_key - Identification required to access private API
```

**Comment by spclinux** [comment]
Yes, same issue here, I get a loop in the "redirect in 5 seconds"

**Comment by bitcoincenter** [comment]
hi,
because of the support lack of mtgox + the fact that customers need an mt gox account with bitcoins on it, i decided to make my own solution.
I started www.bitcoincenter.nl, and i made a very basic magento extension.
Feel free to mail me if you have problems or questions. I finished work today, so its a very beta stadium.

Please, if you want test the system and the magento extension. I would appreciate to hear about your experience.
Short workflow:
1. Signup at www.bitcoincenter.nl
2. Create a merchant inside your account
3. install magento extension. You can find this extension here: https://github.com/bitcoincenter/magento-bitcoincenter_btcpay

This is 100% open source, please commit your improvements if you had some.

On payments we keep a fee of 1% at the moment. Idea is to screw that down to 0.5% in a few weeks.
for development and testing reasons, just mail me. i will reduce your fee to 0.0% , so you dont loose money while testing

**Comment by doncheli** [comment]
Hi all, I discovered a brief and temporary solution to the problem of the Loop, which is to add the Key and Secret in the file (app/code/community/Mtgox/Bitcoin/Helper/data.php) as shown in the figure:

http://screencast.com/t/GWQvxGt76f

I have not had much time to debug, but I think it is being received as expected the Key and Secret info, please if anyone can make a more complete Fix appreciate it.

Greetings.

**Comment by jgautheron** [comment]
Hi,

Thanks @jloronoz for your insight, it was indeed an issue related to the key + secret which just weren't there.
My latest pull request #22 should fix it, do you mind giving it a try?

Cheers!

**Comment by doncheli** [comment]
Hi thanks @jgautheron i'll check this today.

**Comment by kirkwoodgaps** [comment]
Hi, I updated to the latest version of the files, but am still getting the loop at "You will be redirected to the MtGox Payment Platform within 5 seconds."  Any suggestions?

**Comment by jgautheron** [comment]
@kirkwoodgaps if you could provide us with a list of your 3rd party modules and your version of Magento, that would be helpful

**Comment by kirkwoodgaps** [comment]
Magento ver. 1.7.0.2

Apptha One Step Checkout
Lanot Easy Sticker
Recently Sold
MtGox Bitcoin
Color Selector Plus
jquery Lighboxes
Zopim Chat
Amasty Special Promotions
Simple Google Shipping (Wyomind)
Google Base Feed Generator

_Nate Danielson_

T: 561-267-2361
E: natex3000@gmail.com
